# Generated by Django 4.0.3 on 2022-08-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stufname',
            field=models.CharField(default='not available', max_length=30),
        ),
    ]
