# Generated by Django 4.0.3 on 2022-08-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_student_stufname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stufname',
        ),
    ]
